# -*- coding: utf-8 -*-
"""Capstone_Bengkod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ikfinakmlya/capstone_datascience/blob/main/Capstone_Bengkod.ipynb

## Ikfina Kamaliya Rizqi - A11.2022.14170
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings



# Load the dataset
file_path = "ObesityDataSet.csv"
df = pd.read_csv(file_path)

st.title("CAPSTONE PROJECT - DATA SCIENCE ")

st.subheader("1. EDA")

# 1. Tampilkan beberapa baris pertama dan informasi umum dataset
st.write("5 baris pertama:")
st.dataframe(df.head(5))

# Tampilkan jumlah baris dan kolom
st.write("\nJumlah baris dan kolom:")
st.write(f"{df.shape[0]} baris, {df.shape[1]} kolom")

# Tipe data
df = df.replace('?', np.nan)
kolom_numerik = ['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE']
for kol in kolom_numerik:
    df[kol] = pd.to_numeric(df[kol], errors='coerce')
st.write("\nTIPE DATA:")
st.dataframe(df.dtypes)

# Tampilkan deskripsi statistik data numerik
st.write("\nDeskripsi data numerik:")
st.dataframe(df.describe())

# Untuk data kategorikal juga bisa tambahkan:
st.write("\nDeskripsi data kategorikal:")
st.dataframe(df.describe(include=['object']))

# Visualisasi kolom numerik
# Pilih kolom numerik
numerik_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Looping buat plot histogram tiap kolom numerik
for col in numerik_cols:
    plt.figure(figsize=(8, 4))
    sns.histplot(df[col], kde=True, color='orange')
    plt.title(f'Distribusi Kolom Numerik: {col}')
    plt.xlabel(col)
    plt.ylabel('Frekuensi')
    plt.grid(True)
    plt.tight_layout()
    st.pyplot(plt)
    plt.close()

# Visualisasi kolom kategorikal

warnings.simplefilter(action='ignore', category=FutureWarning)

# Pilih kolom kategorikal
kategori_cols = df.select_dtypes(include=['object', 'category']).columns

# Looping buat plot countplot tiap kolom kategorikal
for col in kategori_cols:
    plt.figure(figsize=(8, 4))
    sns.countplot(x=col, data=df, palette='Set2')
    plt.title(f'Distribusi Kategori: {col}')
    plt.xticks(rotation=45)
    plt.tight_layout()
    st.pyplot(plt)
    plt.close()

# Cek Missing Values
st.write("Cek Missing Values:")
st.dataframe(df.isnull().sum())
st.write("\nTotal missing values:", df.isnull().sum().sum())

# Cek Unique Values per Kolom
st.write("\nCek Unique Values per Kolom:")
for col in df.columns:
    st.write(f"{col}: {df[col].nunique()}")

# Cek Data Duplikat
st.write(f"Cek Jumlah data duplikat: {df.duplicated().sum()}")

#Cek keseimbangan seluruh dataset

# Pisahkan kolom numerik & kategorikal
numerik_cols = df.select_dtypes(include=['int64', 'float64']).columns
kategori_cols = df.select_dtypes(include=['object', 'category']).columns

# Cek Keseimbangan Kolom Kategorikal
st.write("Keseimbangan Data - Kolom Kategorikal")
for col in kategori_cols:
    st.write(f"\nDistribusi {col}:")
    st.dataframe(df[col].value_counts(normalize=True) * 100)

    plt.figure(figsize=(6, 4))
    sns.countplot(x=col, data=df, palette='Set2')
    plt.title(f'Distribusi Kategori: {col}')
    plt.xticks(rotation=45)
    plt.tight_layout()
    st.pyplot(plt)
    plt.close()

# Cek Keseimbangan Kolom Numerik
st.write("\nKeseimbangan Data - Kolom Numerik")
for col in numerik_cols:
    plt.figure(figsize=(6, 4))
    sns.histplot(df[col], kde=True, color='orange')
    plt.title(f'Distribusi Nilai: {col}')
    plt.tight_layout()
    st.pyplot(plt)
    plt.close()

# Deteksi outlier kolom numerik menggunakan boxplot
st.write("\nDeteksi Outlier Kolom Numerik dengan Boxplot")
# Pilih kolom numerik
numerik_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Buat boxplot tiap kolom numerik untuk deteksi outlier
for col in numerik_cols:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=df[col], color='orange')
    plt.title(f'Deteksi Outlier dengan Boxplot - Kolom: {col}')
    plt.tight_layout()
    st.pyplot(plt)
    plt.close()

"""Kesimpulan:

Dataset ini terdiri dari 2111 baris dan 17 kolom yang meliputi berbagai atribut seperti Age, Gender, Height, Weight, CALC, FAVC, FCVC, NCP, SCC, SMOKE, CH2O, family\_history\_with\_overweight, FAF, TUE, CAEC, MTRANS, dan NObeyesdad. Dalam proses eksplorasi data ditemukan adanya 300 nilai missing yang tersebar di seluruh kolom serta 18 baris data duplikat yang perlu diatasi agar kualitas data tetap terjaga. Selain itu, deteksi outlier dilakukan khusus pada kolom numerik yaitu Age, Height, Weight, FCVC, NCP, CH2O, FAF, dan TUE menggunakan boxplot untuk mengidentifikasi nilai-nilai ekstrim yang berpotensi memengaruhi analisis lebih lanjut.

# 2. Preprocessing Data
"""

# Cek missing values dan imputasi
# Contoh pendekatan sederhana: Imputasi berdasarkan tipe data
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if df[col].dtype == 'object':
            mode_val = df[col].mode()[0]
            df[col] = df[col].fillna(mode_val)
            st.write(f"Kolom '{col}' (tipe object) diisi dengan modus: {mode_val}")
        else:
            median_val = df[col].median()
            df[col] = df[col].fillna(median_val)
            st.write(f"Kolom '{col}' (tipe numerik) diisi dengan median: {median_val}")

st.write("\nMissing value setelah imputasi:")
st.dataframe(df.isnull().sum())
st.write("Total:", df.isnull().sum().sum())

# Tangani Duplikat
st.write(f"\nJumlah Duplikasi Sebelum: {df.duplicated().sum()}")
df = df.drop_duplicates()
st.write(f"Jumlah Duplikasi Setelah: {df.duplicated().sum()}")

# Tangani Eror (Contoh validasi kolom numerik tidak bernilai negatif (misalnya kolom umur atau harga))
for col in df.select_dtypes(include=np.number).columns:
    if (df[col] < 0).any():
        st.write(f"Error nilai negatif ditemukan di kolom: {col}, akan diganti dengan median")
        df.loc[df[col] < 0, col] = df[col].median()

# Tangani Outlier
def remove_outliers_iqr(data, col):
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return data[(data[col] >= lower_bound) & (data[col] <= upper_bound)]

# Terapkan pada semua kolom numerik
for col in df.select_dtypes(include=np.number).columns:
    original_len = len(df)
    df = remove_outliers_iqr(df, col)
    st.write(f"Outlier dihapus dari kolom '{col}': {original_len - len(df)} baris")

# Cek kolom kategorik
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
st.write("Kolom kategorik:", list(categorical_cols))

# Pilih metode
if len(categorical_cols) > 0:
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
    st.write("Semua kolom kategorik diubah jadi numerik dengan one-hot encoding.")
else:
    st.write("Tidak ada kolom kategorik yang perlu dikonversi.")

st.dataframe(df.info())  # semua kolom sekarang numerik (int/float)

# tentukan apakah semua feature perlu digunakan.

from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.01)  # Fitur dengan variansi < 1% dibuang
selector.fit(df.drop('NObeyesdad_Overweight_Level_II', axis=1))

low_variance_features = df.drop('NObeyesdad_Overweight_Level_II', axis=1).columns[~selector.get_support()]
st.write("Fitur variansi rendah:", list(low_variance_features))

"""fitur-fitur ini kemungkinan besar tidak banyak memberi informasi tambahan, karena nilainya hampir sama di semua baris."""

df = df.drop(['Height', 'MTRANS_Bike', 'MTRANS_Motorbike'], axis=1)
st.write("Fitur variansi rendah sudah dihapus.")

"""Fitur variansi rendah sudah dihapus."""

plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(numeric_only=True), annot=False, cmap='coolwarm')
plt.title("Korelasi antar fitur")
st.pyplot(plt)
plt.close()

st.write(df['NObeyesdad_Overweight_Level_II'].value_counts())
st.write(df['NObeyesdad_Overweight_Level_II'].value_counts(normalize=True))  # dalam persen

"""tidak seimbang.
Kelas True (Overweight Level II) cuma 12%, artinya model bisa bias ke kelas False.
"""

from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Kolom untuk standarisasi (nilai besar, bisa negatif/positif)
standard_cols = ['Age', 'Weight']

# Kolom untuk normalisasi (range kecil dan positif)
minmax_cols = [
    'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE',
    'Gender_Male', 'FAVC_yes', 'SCC_yes', 'SMOKE_yes',
    'family_history_with_overweight_yes',
    'CAEC_Frequently', 'CAEC_Sometimes', 'CALC_no', 'CALC_Sometimes'
]

# Standarisasi (Ubah data ke distribusi dengan mean=0 dan sandar deviasi=1)
st.write("STANDARISASI:")
scaler_std = StandardScaler()
df[standard_cols] = scaler_std.fit_transform(df[standard_cols])
st.write(df[standard_cols].describe())

# Normalisasi (semua nilai berada di rentang 0,1 menggunakan minmax)
st.write("NORMALISASI:")
scaler_mm = MinMaxScaler()
df[minmax_cols] = scaler_mm.fit_transform(df[minmax_cols])
st.write(df[minmax_cols].describe())

"""Kesimpulan:

Setelah dilakukan proses pembersihan data, tidak ditemukan missing value karena seluruh nilai yang kosong telah berhasil diimputasi. Selain itu, sebanyak 20 baris duplikat berhasil dihapus untuk menghindari redundansi data. Outlier pada beberapa kolom seperti Age, Height, Weight, dan lain-lain juga telah diidentifikasi dan dihapus guna meningkatkan kualitas dan keandalan model. Data kategorik yang terdapat pada kolom seperti Gender, CALC, FAVC, SCC, SMOKE, family\_history\_with\_overweight, CAEC, MTRANS, dan NObeyesdad telah diubah menjadi bentuk numerik menggunakan teknik One-Hot Encoding agar bisa diproses oleh model machine learning. Selanjutnya, dilakukan seleksi fitur dengan metode Variance Threshold, dan fitur dengan variansi rendah seperti Height, MTRANS\_Bike, dan MTRANS\_Motorbike telah dihapus karena dianggap tidak memberikan informasi yang signifikan. Distribusi target kelas pada label NObeyesdad\_Overweight\_Level\_II menunjukkan ketidakseimbangan yang signifikan, dengan hanya 12% data termasuk dalam kelas True, yang berarti perlu penanganan khusus pada tahap modeling agar model tidak bias terhadap kelas mayoritas. Terakhir, dilakukan standarisasi menggunakan StandardScaler pada kolom Age dan Weight untuk mengubah distribusi menjadi memiliki mean 0 dan standar deviasi 1, serta normalisasi menggunakan MinMaxScaler pada kolom seperti FCVC, NCP, CH2O, FAF, TUE, dan beberapa kolom dummy lainnya untuk menyamakan skala nilai dalam rentang 0 hingga 1.

# 3. Pemodelan dan Evaluasi

print(df.columns.tolist())
"""

st.write(df.columns.tolist())

# Gabungkan kolom one-hot target menjadi 1 kolom label
target_cols = ['NObeyesdad_Normal_Weight',
               'NObeyesdad_Obesity_Type_I',
               'NObeyesdad_Obesity_Type_II',
               'NObeyesdad_Obesity_Type_III',
               'NObeyesdad_Overweight_Level_I',
               'NObeyesdad_Overweight_Level_II']

# Ambil X (fitur) dan y (label)
X = df.drop(columns=target_cols)
y = df[target_cols].idxmax(axis=1)  # Ambil nama kolom target yang nilainya 1

# Contoh hasil y: 'NObeyesdad_Obesity_Type_I'
# Kalau mau bersihin prefixnya:
y = y.str.replace('NObeyesdad_', '')

# Lanjut split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Logistic Regression
model_logreg = LogisticRegression(max_iter=1000, random_state=42)
model_logreg.fit(X_train, y_train)
y_pred_logreg = model_logreg.predict(X_test)

# Decision Tree
model_tree = DecisionTreeClassifier(random_state=42)
model_tree.fit(X_train, y_train)
y_pred_tree = model_tree.predict(X_test)

# Random Forest
model_forest = RandomForestClassifier(n_estimators=100, random_state=42)
model_forest.fit(X_train, y_train)
y_pred_forest = model_forest.predict(X_test)

# Fungsi untuk menghitung metrik evaluasi dan visualisasi confusion matrix
def evaluate_model(y_test, y_pred, model_name):
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)
    cm = confusion_matrix(y_test, y_pred)

    # Visualisasi Confusion Matrix
    plt.figure(figsize=(7, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, linewidths=0.5, linecolor='gray')
    plt.title(f'Confusion Matrix - {model_name}')
    plt.ylabel('Actual')  # Baris
    plt.xlabel('Predicted')  # Kolom
    st.pyplot(plt)
    plt.close()

    return {'Model': model_name, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1-Score': f1}

# Evaluasi masing-masing model
results = []
results.append(evaluate_model(y_test, y_pred_logreg, "Logistic Regression"))
results.append(evaluate_model(y_test, y_pred_tree, "Decision Tree"))
results.append(evaluate_model(y_test, y_pred_forest, "Random Forest"))

# Membuat tabel perbandingan
results_df = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score'],
    'Logistic Regression': [results[0]['Accuracy'], results[0]['Precision'], results[0]['Recall'], results[0]['F1-Score']],
    'Decision Tree': [results[1]['Accuracy'], results[1]['Precision'], results[1]['Recall'], results[1]['F1-Score']],
    'Random Forest': [results[2]['Accuracy'], results[2]['Precision'], results[2]['Recall'], results[2]['F1-Score']]
})

# Menampilkan tabel s
st.write("\nTabel Perbandingan Model:")
col_widths = {
    'Metric': 12,
    'Logistic Regression': 20,
    'Decision Tree': 15,
    'Random Forest': 15
}
formatted_table = results_df.to_string(index=False, formatters={
    'Logistic Regression': '{:.4f}'.format,
    'Decision Tree': '{:.4f}'.format,
    'Random Forest': '{:.4f}'.format
}, col_space=col_widths)
st.write(formatted_table)

# Visualisasi perbandingan metrik
results_df.set_index('Metric').plot(kind='bar', figsize=(10, 6), color=['#1f77b4', '#ff7f0e', '#2ca02c'])
plt.title('Perbandingan Metrik Antar Model')
plt.ylabel('Nilai')
plt.xlabel('Metrik')
plt.xticks(rotation=0)
plt.legend(title='Model')
plt.tight_layout()
st.pyplot(plt)
plt.close()

"""Kesimpulan:

Target klasifikasi adalah kolom NObeyesdad, yang awalnya diubah menjadi one-hot encoding dengan enam kelas: Normal_Weight, Obesity_Type_I, Obesity_Type_II, Obesity_Type_III, Overweight_Level_I, dan Overweight_Level_II. Setelah preprocessing, prefiks NObeyesdad_ dihapus untuk menyederhanakan label menjadi Normal_Weight, Obesity_Type_I, dan seterusnya.
Proses dimulai dengan pemisahan fitur X dari semua kolom kecuali target, sementara target y dihasilkan dengan idxmax() untuk memilih kelas dengan nilai 1 dari one-hot encoding.
Data kemudian dibagi menjadi data latih X_train, y_train dan data uji X_test, y_test dengan rasio 80:20 untuk memastikan konsistensi.
Karena ini adalah klasifikasi multi-kelas dengan enam kelas, "Actual" merujuk pada label asli dari data uji y_test, sedangkan "Predicted" adalah tebakan model berdasarkan data latih, yang dibandingkan dalam confusion matrix untuk mengevaluasi performa.

Tiga model klasifikasi diterapkan: Logistic Regression, Decision Tree, dan Random Forest. Setiap model dilatih, lalu evaluasi dilakukan untuk menangani ketidakseimbangan kelas.
Berdasarkan hasil, Random Forest menunjukkan performa terbaik dengan akurasi tertinggi sebesar 0.9167, diikuti oleh Precision 0.9164, Recall 0.9167, dan F1-Score 0.9131, menunjukkan konsistensi di atas 0.91. Logistic Regression mencatat akurasi 0.8750 dengan Precision 0.8838, Recall 0.8750, dan F1-Score 0.8736, sementara Decision Tree memiliki akurasi 0.8636 dengan Precision 0.8635, Recall 0.8636, dan F1-Score 0.8635.
Hasil ini mengindikasikan bahwa Random Forest lebih unggul dalam memprediksi tingkat obesitas dibandingkan kedua model lain, kemungkinan karena kemampuannya menangkap pola kompleks melalui ensembel pohon keputusan.

# 4. Hyperparameter Tuning

untuk menemukan kombinasi parameter terbaik yang memberikan performa optimal pada model
"""

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# 1. Grid Search untuk Logistic Regression
param_grid_logreg = {
    'C': [0.01, 0.1, 1, 10], #Logistic Regression
    # C= inverse dari regularization strength (kebalikan dari kekuatan regularisasi).
    'solver': ['lbfgs', 'liblinear']
}

grid_logreg = GridSearchCV(LogisticRegression(max_iter=1000, random_state=42),
                           param_grid_logreg, cv=5, n_jobs=-1, scoring='accuracy')
grid_logreg.fit(X_train, y_train)
st.write("Best Logistic Regression:", grid_logreg.best_params_)

# 2. Grid Search untuk Decision Tree
param_grid_tree = {
    'criterion': ['gini', 'entropy'],
     #menentukan fungsi yang digunakan untuk mengukur kualitas pemisahan di setiap pohon, pemilihan standar
    'max_depth': [None, 5, 10, 20], #Decision Tree dan Random Forest
     #10: Kedalaman sedang untuk mengurangi risiko overfitting,
    #20: Kedalaman lebih dalam untuk menangkap pola yang lebih kompleks, tetapi masih dibatasi.
    'min_samples_split': [2, 5, 10] #Nilai minimum, Membutuhkan setidaknya 5 sampel, Membutuhkan 10 sampel, lebih konservatif dan cocok untuk dataset dengan noise.
}

grid_tree = GridSearchCV(DecisionTreeClassifier(random_state=42),
                         param_grid_tree, cv=5, n_jobs=-1, scoring='accuracy')
grid_tree.fit(X_train, y_train)
st.write("Best Decision Tree:", grid_tree.best_params_)

# 3. Grid Search untuk Random Forest
param_grid_forest = {
    'n_estimators': [50, 100, 150], # Random Forest
    #50: Jumlah pohon kecil untuk model yang lebih cepat, cocok untuk eksperimen awal.
    #100: Nilai standar yang sering digunakan sebagai baseline, memberikan keseimbangan antara performa dan waktu.
    #150: Nilai lebih besar untuk melihat apakah menambah pohon meningkatkan akurasi.
    #jumlah pohon keputusan yang dibuat dalam Random Forest
    'max_depth': [None, 10, 20], # Decision Tree dan Random Forest,
    #10: Kedalaman sedang untuk mengurangi risiko overfitting,
    #20: Kedalaman lebih dalam untuk menangkap pola yang lebih kompleks, tetapi masih dibatasi.
    'min_samples_split': [2, 5], #nilai minimum, 5 sampel untuk berbagi node
    'criterion': ['gini', 'entropy']
    #menentukan fungsi yang digunakan untuk mengukur kualitas pemisahan di setiap pohon, pemilihan standar
}

grid_forest = GridSearchCV(RandomForestClassifier(random_state=42),
                           param_grid_forest, cv=5, n_jobs=-1, scoring='accuracy')
grid_forest.fit(X_train, y_train)
st.write("Best Random Forest:", grid_forest.best_params_)

"""- Logistic :
  - C=10 ; regularisasi lemah → model boleh lebih fleksibel.
  - solver: 'lbfgs' Parameter solver menentukan algoritma optimasi yang digunakan untuk melatih model.

- Decision:
  - criterion: menentukan metrik yang digunakan untuk membagi simpul (node) pada pohon keputusan.
  - entropy menggunakan Information Gain berdasarkan entropi (ukuran ketidakpastian).
  Ini berarti model memilih pemisahan yang paling mengurangi ketidakpastian dalam data.
  - max_depth: untuk mengontrol kedalaman maksimum pohon.
  - None berarti pohon akan berkembang hingga semua daun murni (tidak ada campuran kelas)
  - min_samples_split: menentukan jumlah minimum sampel yang diperlukan untuk membagi simpul.
  - Nilai 5 berarti simpul hanya akan dibagi jika ada setidaknya 5 sampel di simpul tersebut.

- Random:
  - criterion dan max depth sama kaya decision
  - min_samples_split: 2
  - Nilai 2 adalah default untuk Random Forest, yang berarti simpul akan dibagi selama ada minimal 2 sampel.
  - n_estimators: menentukan jumlah pohon dalam Random Forest.
  - Nilai 100 adalah pilihan yang umum dan seimbang—cukup banyak untuk memastikan stabilitas prediksi melalui voting,
"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Simpan performa sebelum tuning (model dengan parameter default)
model_logreg_before = LogisticRegression(max_iter=1000, random_state=42)
model_logreg_before.fit(X_train, y_train)
y_pred_logreg_before = model_logreg_before.predict(X_test)

model_tree_before = DecisionTreeClassifier(random_state=42)
model_tree_before.fit(X_train, y_train)
y_pred_tree_before = model_tree_before.predict(X_test)

model_forest_before = RandomForestClassifier(n_estimators=100, random_state=42)
model_forest_before.fit(X_train, y_train)
y_pred_forest_before = model_forest_before.predict(X_test)

# Latih ulang model dengan hyperparameter terbaik
# Logistic Regression
model_logreg = LogisticRegression(C=10, solver='lbfgs', max_iter=1000, random_state=42)
model_logreg.fit(X_train, y_train)
y_pred_logreg = model_logreg.predict(X_test)

# Decision Tree
model_tree = DecisionTreeClassifier(criterion='entropy', max_depth=None, min_samples_split=5, random_state=42)
model_tree.fit(X_train, y_train)
y_pred_tree = model_tree.predict(X_test)

# Random Forest
model_forest = RandomForestClassifier(criterion='entropy', max_depth=None, min_samples_split=2, n_estimators=100, random_state=42)
model_forest.fit(X_train, y_train)
y_pred_forest = model_forest.predict(X_test)

# Fungsi untuk evaluasi dan visualisasi
def evaluate_model(y_test, y_pred, model_name, y_pred_before=None):
    # Metrik setelah tuning
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)
    cm = confusion_matrix(y_test, y_pred)

    # Metrik sebelum tuning
    accuracy_before = None
    precision_before = None
    recall_before = None
    f1_before = None

    if y_pred_before is not None:
        accuracy_before = accuracy_score(y_test, y_pred_before)
        precision_before = precision_score(y_test, y_pred_before, average='weighted', zero_division=0)
        recall_before = recall_score(y_test, y_pred_before, average='weighted', zero_division=0)
        f1_before = f1_score(y_test, y_pred_before, average='weighted', zero_division=0)

        st.write(f"\nPerbandingan untuk {model_name}:")
        st.write(f"Sebelum Tuning - Accuracy: {accuracy_before:.4f}, Precision: {precision_before:.4f}, Recall: {recall_before:.4f}, F1-Score: {f1_before:.4f}")
        st.write(f"Setelah Tuning - Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-Score: {f1:.4f}")
        st.write(f"Peningkatan Akurasi: {(accuracy - accuracy_before):.4f}")
        st.write(f"Peningkatan Precision: {(precision - precision_before):.4f}")
        st.write(f"Peningkatan Recall: {(recall - recall_before):.4f}")
        st.write(f"Peningkatan F1-Score: {(f1 - f1_before):.4f}")

    # Visualisasi Confusion Matrix
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f'Confusion Matrix - {model_name} (Setelah Tuning)')
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    st.pyplot(plt)
    plt.close()

    return {
        'Model': model_name,
        'Accuracy (Sebelum)': accuracy_before,
        'Precision (Sebelum)': precision_before,
        'Recall (Sebelum)': recall_before,
        'F1-Score (Sebelum)': f1_before,
        'Accuracy (Setelah)': accuracy,
        'Precision (Setelah)': precision,
        'Recall (Setelah)': recall,
        'F1-Score (Setelah)': f1
    }

# Evaluasi masing-masing model
results = []
results.append(evaluate_model(y_test, y_pred_logreg, "Logistic Regression", y_pred_logreg_before))
results.append(evaluate_model(y_test, y_pred_tree, "Decision Tree", y_pred_tree_before))
results.append(evaluate_model(y_test, y_pred_forest, "Random Forest", y_pred_forest_before))

# Pisahkan hasil menjadi dua tabel
before_tuning = [
    {
        'Model': result['Model'],
        'Accuracy': result['Accuracy (Sebelum)'],
        'Precision': result['Precision (Sebelum)'],
        'Recall': result['Recall (Sebelum)'],
        'F1-Score': result['F1-Score (Sebelum)']
    }
    for result in results
]
before_df = pd.DataFrame(before_tuning)

after_tuning = [
    {
        'Model': result['Model'],
        'Accuracy': result['Accuracy (Setelah)'],
        'Precision': result['Precision (Setelah)'],
        'Recall': result['Recall (Setelah)'],
        'F1-Score': result['F1-Score (Setelah)']
    }
    for result in results
]
after_df = pd.DataFrame(after_tuning)

# Tampilkan tabel
st.write("\nPerforma Model Sebelum Tuning")
st.dataframe(before_df)
st.write("\nPerforma Model Sesudah Tuning")
st.dataframe(after_df)

# Visualisasi perbandingan performa (hanya Accuracy)
models = before_df['Model']
accuracy_before = before_df['Accuracy']
accuracy_after = after_df['Accuracy']

x = np.arange(len(models))  # Posisi label
width = 0.35  # Lebar batang

fig, ax = plt.subplots(figsize=(8, 5))
bars1 = ax.bar(x - width/2, accuracy_before, width, label='Sebelum Tuning', color='skyblue')
bars2 = ax.bar(x + width/2, accuracy_after, width, label='Sesudah Tuning', color='lightgreen')

# Label dan judul
ax.set_ylabel('Accuracy')
ax.set_title('Perbandingan Performa Model (Accuracy) Sebelum dan Sesudah Tuning')
ax.set_xticks(x)
ax.set_xticklabels(models)
ax.legend()

# Tampilkan grafik
plt.tight_layout()
st.pyplot(plt)
plt.close()

"""Keisimpulan:

Proses optimasi hyperparameter dilakukan menggunakan **GridSearchCV** untuk tiga model klasifikasi.
Logistic Regression diuji dengan parameter C (kekuatan regularisasi terbalik: 0.01, 0.1, 1, 10) dan solver ('lbfgs', 'liblinear') untuk menemukan kombinasi terbaik guna meningkatkan akurasi, dengan iterasi maksimum 1000 dan seed acak 42.
Decision Tree dioptimalkan melalui parameter criterion ('gini', 'entropy'), max_depth (None, 5, 10, 20) untuk mengatur kedalaman pohon, serta min_samples_split (2, 5, 10) guna mengontrol pemisahan node, dengan fokus pada akurasi melalui validasi silang 5 lipat.
Sementara itu, Random Forest diuji dengan parameter n_estimators (50, 100, 150) untuk jumlah pohon, max_depth (None, 10, 20), min_samples_split (2, 5), dan criterion ('gini', 'entropy'), memanfaatkan semua prosesor (`n_jobs=-1`) dan validasi silang 5 lipat untuk menemukan parameter optimal.
Setelah melatih ulang model dengan parameter terbaik dan mengevaluasi kembali performanya, hasil menunjukkan peningkatan akurasi pada Model Logistic Regression meningkat dari 0,8750 menjadi 0,8939, Decision Tree dari 0,8638 menjadi 0,9053, dan Random Forest dari 0,9167 menjadi 0,9470, menunjukkan efektivitas proses optimasi hyperparameter dalam meningkatkan performa model.
"""